version: '3.8'
services:
  app:
    build: .
    container_name: laravel_app
    ports:
      - "8000:8000"
    volumes:
    - .:/var/www/html
    - /var/www/html/vendor
    depends_on:
      - db
    networks:
      - laravel_network
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: llkc_db
      DB_USERNAME: llkc_user
      DB_PASSWORD: llkc_password
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: llkc_db
      MYSQL_USER: llkc_user
      MYSQL_PASSWORD: llkc_password
    ports:
      - "3306:3306"
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge
