version: '3.8'

services:
  app:
    build: .
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      - APP_ENV=local
      - DB_HOST=mysql
      - DB_PORT=3306

  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: llkc
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  node:
    image: node:20
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: ["npm", "run", "dev"]
